name: Pull Request Tests

on: [pull_request]

jobs:
  #########
  # Tests #
  #########
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Dart Pub Get
        timeout-minutes: 3
        run: dart pub get

      - name: Dart Analyze
        timeout-minutes: 3
        run: dart analyze --fatal-infos

      - name: Dart Test
        run: dart test
