name: Pull Request Tests

on: [pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false

      - name: Dart Pub Get
        timeout-minutes: 3
        run: dart pub get

      - name: Dart Analyze
        timeout-minutes: 3
        run: dart analyze --fatal-infos

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: $GITHUB_REPOSITORY_OWNER
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Dart Test
        run: dart test
